# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application files
COPY server.js ./

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["node", "server.js"]