
services:
  # Backend service
  backend:
    build:
      context: ../backend  # Set the build context to the backend directory
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      DB_HOST: db  # Reference to the MariaDB container
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: "5000"
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db  # Ensures the backend waits for the db service to start before it starts
    env_file:
      - .env  # Ensure the environment variables are loaded from the .env file

  # Database service (MariaDB)
  db:
    build:
      context: ../mariadb  # The directory containing your Dockerfile (root of the project or adjust accordingly)
      dockerfile: Dockerfile.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Persist database data across restarts
    ports:
      - "${MARIADB_PORT}:3306"  # Expose MariaDB port to the host
    env_file:
      - .env  # Environment variables for MariaDB

 # Vue.js frontend service
  frontend:
    build:
      context: ../vue  # Set the build context to the vue directory
      dockerfile: Dockerfile.vue
    ports:
      - "${CLIENT_PORT}:80"  # Expose the frontend on port 8080
    depends_on:
      - backend  # Ensure the frontend waits for the backend to be ready
    environment:
      CLIENT_URL: ${CLIENT_URL}
      BACKEND_URL: ${BACKEND_URL}
      VUE_APP_STRIPE_PUBLISHABLE_KEY: ${VUE_APP_STRIPE_PUBLISHABLE_KEY}

# Volumes for persisting data
volumes:
  db_data:
